create table if not exists public.tcp_client_events (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    event_time timestamptz,
    line_id text not null,
    event_type text not null,
    code_type text,
    code text,
    message text,
    ip text,
    port text
);

alter table public.tcp_client_events enable row level security;

-- Allows the TCP Client app to insert events using the anon key.
-- Keep SELECT closed unless a dashboard/web page needs it.
drop policy if exists "tcp client can insert events" on public.tcp_client_events;
create policy "tcp client can insert events"
on public.tcp_client_events
for insert
to anon
with check (true);

-- Optional for a web dashboard that reads with logged-in users.
-- Enable only if the website uses Supabase Auth.
drop policy if exists "authenticated users can read events" on public.tcp_client_events;
create policy "authenticated users can read events"
on public.tcp_client_events
for select
to authenticated
using (true);
